fix English spelling
libremesh/lime-app pull request #304
Opened 2021-03-28 12:31 UTC by luandro

Minor fix on English spelling.

2021-03-28 12:36 UTC, ilario approved these changes

2021-03-29 00:26 UTC, nicopace approved these changes

2021-03-31 12:43 UTC, germanferrero requested changes
Hi @luandro sorry for being late to review this PR :)

The file generic.json is always overwritten by `npm run translations`, so we shouldn't edit it manually.
Instead, if there is some translation involving pluralization, that translation should be left as is in generic.json and edited in the file en.json

Let me know if you want me to go ahead with this changes.

2021-04-05 21:30 UTC, germanferrero commented
@luandro I've add this little changes :) Thank you again!

2021-04-05 21:30 UTC, merged