Add pt-br translations
libremesh/lime-app pull request #305
Opened 2021-03-28 13:35 UTC by luandro

Português do Brasil! :brazil:

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +  "applying_changes_23ae34f2": "Aplicanto mudanças",
Aplicando*

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +  "at_least_one_alphanumeric_character_357817ee": "Ao menos um caractere alphanumérico",
Alfanumérico

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +      "one": "Uma pessoa se uniu a sessão",
à

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +      "other": "%{count} pessoas se uniram a sessão",
à

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +      "zero": "Ninguém se uniu a sessão"
à

2021-03-28 14:55 UTC, brunovianna commented on i18n/translations/pt-br.json
> +  "join_the_mesh_653219c6": "Se junte a rede",
à

2021-03-28 21:26 UTC, luandro commented
:pray: Thank you @brunovianna!

2021-03-31 13:22 UTC, germanferrero requested changes
Thank you so much @luandro  and @brunovianna  for this contribution :)

I left a comment for a tinny fix that needs to be done

2021-03-31 13:22 UTC, germanferrero commented on i18n/translations/pt-br.json
> +      "other": "%{count} dias"
%{count} will duplicate number rendering here.

It should be "dias" instead of "%{count} dias". The same for seconds, minutes and hours :)

2021-03-31 13:22 UTC, germanferrero commented on i18n/translations/pt-br.json
> +      "other": "%{count} dias"
Following en.json or es.json format

2021-04-05 21:34 UTC, germanferrero commented on i18n/translations/pt-br.json
> +      "other": "%{count} dias"
@luandro I've done this little fix!

2021-04-05 21:34 UTC, merged