fixed(getVoices): used an if to check compability with speechsyntesis
libremesh/lime-app pull request #320
Opened 2021-07-11 21:24 UTC by Patacon13

This PR adds a fix that checks if the navigator has compatibility with speechsyntesis before use it.

Without checking it, on some navigators (like WebView) the page doesn't load, showing a white screen without any information. As we're building a network capability app for the LibreMesh routers, we tried it on the app, and got these logs:

![imagen](https://user-images.githubusercontent.com/42981462/125210091-e1a90900-e273-11eb-981b-bbd1af10c2d2.png)

The fix consists of checking if the object is defined, and proceed or not.

2021-07-11 23:21 UTC, nicopace approved these changes
Well spotted Tomas. Thanks for the contribution!

2021-07-12 13:11 UTC, germanferrero requested changes
Thanks @Patacon13, please fix the comparison with undefined. We should do it like this: synth !== undefined (not "undefined")

2021-07-15 18:06 UTC, Patacon13 commented
Thanks! I modified the if condition and now it's using '!=='

2021-07-17 13:11 UTC, nicopace commented
it is good to go for me

2021-07-20 03:11 UTC, germanferrero approved these changes

2021-07-20 03:11 UTC, merged

2021-07-20 03:12 UTC, germanferrero commented
Thanks @Patacon13! And congrats for your first contribution to the LimeApp :)