Feature/fbw show scan results
libremesh/lime-app pull request #339
Opened 2022-04-15 08:09 UTC by selankon

It implements new FBW scanning screen where:

- It shows the backend network scanning results before complete network configuration file download.
- Once a configuration file is downloaded, show node and network name, and let you choose to connect although other configuration files are not already downloaded. 

Together with  https://github.com/selankon/lime-packages/tree/feature/fbw-verbose-scanning

2022-05-12 14:21 UTC, selankon commented
All cases example:

![photo_2022-05-05_17-11-02](https://user-images.githubusercontent.com/16777076/168097039-431c87f4-dac0-4ba4-88cd-b19b9bad4ba1.jpg)

2022-05-20 14:19 UTC, germanferrero requested changes
@selankon great work! It's really awesome to see you involved in the LimeApp development in this depth!

I've let you inline comments for you to review.
Regarding Scan.js file, we can setup a video call to discuss about it if you find it useful

Bests!

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/FbwPage.spec.js
> +        // eslint-disable-next-line jest/valid-expect
Usually `expect` is used along with a `matcher`, in order to be explicit about what is your expectation.
In this case, the matcher could be `.toBeInTheDocument` from 'jest-dom' library.
By using it, you can avoid eslint-disable comment.

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/FbwPage.spec.js
> +        // eslint-disable-next-line jest/valid-expect
Same here

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/FbwPage.spec.js
> +    it('test scan results contain all cases', async () => {
It's not clear which use case we are testing here.
From the code I can guess we are testing that in the case of a scanned node for which the config was successfully downloaded the screen shows up the community name.
In that case, a meaningful test name could be:
"shows community name for results with successful config download"

For this, and all the following test case, to ensure you are rendering the correct message for each status code, you should first get the tile based on the bssid, and then search within the tail, as you did in  'join to existing network from scan results'.

By the way, I didn't know about "within", great tool :tada:

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/FbwApi.js
> +const responseWifiOnly = JSON.parse(`{
Mock implementation here!

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/containers/Scan.js
> +
Let's do the _todo_ before merging

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/containers/Scan.js
>  export const Scan = ({ toggleForm, setExpectedHost, setExpectedNetwork }) => {
This component got huge, It found it difficult to follow the code.
I think that a good first step toward making it more clear could be to separate both screens: the one listing the scanned networks, and the one in which you configure a hostname, in two different files.

2022-05-20 14:19 UTC, germanferrero commented on plugins/lime-plugin-fbw/src/style.less
> +
For the future, we need to define a Design System for the LimeApp, in which general rules for type and spacing are defined, so we avoid each component having specific rules.
To show you what I mean: https://tailwindcss.com/docs/utility-first

2022-05-26 07:57 UTC, selankon commented on plugins/lime-plugin-fbw/src/FbwPage.spec.js
> +        // eslint-disable-next-line jest/valid-expect
Ok, this code is not mine, it was here before and I added this lines because husky doesn't let me commit. I fixed as you said

2022-05-26 08:09 UTC, selankon commented on plugins/lime-plugin-fbw/src/FbwPage.spec.js
> +    it('test scan results contain all cases', async () => {
Uups... I forgot to write good test name here! 

Better here? d1b54a0

2022-05-26 08:58 UTC, selankon commented on plugins/lime-plugin-fbw/src/containers/Scan.js
> +
See this 28888c3

2022-08-08 12:46 UTC, germanferrero approved these changes
Solid code!

2022-08-10 09:31 UTC, selankon commented
Hopefully this is ready to merge among with https://github.com/libremesh/lime-packages/pull/925

2022-09-23 10:03 UTC, selankon commented
Following figma suggestions, I refactored lime fbw banner to fit this requirements: 

![image](https://user-images.githubusercontent.com/16777076/191937718-5ec50831-ad70-4b25-9b23-e8ef52cea0d8.png)

2022-10-06 08:19 UTC, merged